---
title: "Coinoculation"
author: "James C. Kosmopoulos"
date: "`r format(Sys.Date())`"
output: github_document
editor_options: 
  chunk_output_type: console
---

# Setup

```{r Load packages, message=FALSE, warning=FALSE}
# global options
knitr::opts_chunk$set(echo = TRUE)

# set working directory
setwd("~/Documents/Research/co-inoculation/coinoculation")

# load packages
library("tidyverse") # includes ggplot2, dplyr, readr, stringr
library("knitr") # produce the knitted doc
library("emmeans") # for posthoc data analysis
library("lme4") # linear mixed models
library("car") # ANOVA function for linear mixed models
library("gridExtra") # for arranging plots
library("cowplot")
```


# Summarize,organize, and save cleaned data

```{r, echo = FALSE, warning = FALSE}
tp_raw <- read_csv("all_data.csv")

# removed outliers "InCtrl-2-r15", "733B-17-r27", "717A-6-r33" 
tp_all <- read.csv("./tp_all.csv")

# rearrange treatment levels to make figures look better
tp_all$treatment <- tp_all$treatment %>% levels(c("InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141"))

tp_all_sum <- tp_all %>%
  group_by(type) %>%
  summarize(count = n(),
            # timepoint1 data
            # height
            mean_height1 = mean(height1, na.rm = TRUE), sd_height1 = sd(height1, na.rm = TRUE),
            SE_height1 = sd_height1/sqrt(count),
            # chlorophyll
            mean_chloro1 = mean(chloro1, na.rm = TRUE), sd_chloro1 = sd(chloro1, na.rm = TRUE),
            SE_chloro1 = sd_chloro1/sqrt(count),
            # leaf
            mean_leaf1 = mean(leaf1, na.rm = TRUE), sd_leaf1 = sd(leaf1, na.rm = TRUE),
            SE_leaf1 = sd_leaf1/sqrt(count),

            # timepoint2 data
            # height
            mean_height2 = mean(height2, na.rm = TRUE), sd_height2 = sd(height2, na.rm = TRUE),
            SE_height2 = sd_height2/sqrt(count),
            # chlorophyll
            mean_chloro2 = mean(chloro2, na.rm = TRUE), sd_chloro2 = sd(chloro2, na.rm = TRUE),
            SE_chloro2 = sd_chloro2/sqrt(count),
            # leaf
            mean_leaf2 = mean(leaf2, na.rm = TRUE), sd_leaf2 = sd(leaf2, na.rm = TRUE),
            SE_leaf2 = sd_leaf2/sqrt(count),

            # timepoint3 data
            # height
            mean_height3 = mean(height3, na.rm = TRUE), sd_height3 = sd(height3, na.rm = TRUE),
            SE_height3 = sd_height3/sqrt(count),
            # chlorophyll
            mean_chloro3 = mean(chloro3, na.rm = TRUE), sd_chloro3 = sd(chloro3, na.rm = TRUE),
            SE_chloro3 = sd_chloro3/sqrt(count),
            # leaf
            mean_leaf3 = mean(leaf3, na.rm = TRUE), sd_leaf3 = sd(leaf3, na.rm = TRUE),
            SE_leaf3 = sd_leaf3/sqrt(count),
            
            # timepoint4 data
            # height
            mean_height4 = mean(height4, na.rm = TRUE), sd_height4 = sd(height4, na.rm = TRUE),
            SE_height4 = sd_height4/sqrt(count),
            # chlorophyll
            mean_chloro4 = mean(chloro4, na.rm = TRUE), sd_chloro4 = sd(chloro4, na.rm = TRUE),
            SE_chloro4 = sd_chloro4/sqrt(count),
            # leaf
            mean_leaf4 = mean(leaf4, na.rm = TRUE), sd_leaf4 = sd(leaf4, na.rm = TRUE),
            SE_leaf4 = sd_leaf4/sqrt(count),
            
            # nodule dissection data
            # mean nodule mass per tube
            mean_nod_mass = mean(nod_mass, na.rm = TRUE),
            sd_nod_mass = sd(nod_mass, na.rm = TRUE),
            SE_nod_mass = sd_nod_mass/sqrt(count),
            # total nodules per tube
            mean_total_nod = mean(total_nod, na.rm = TRUE),
            sd_total_nod = sd(total_nod, na.rm = TRUE),
            SE_total_nod = sd_total_nod/sqrt(count),
            
            # biomass
            # mean shoot biomass (mg)
            mean_shoot_mass = mean(shoot_mass, na.rm = TRUE),
            sd_shoot_mass = sd(shoot_mass, na.rm = TRUE),
            SE_shoot_mass = sd_shoot_mass/sqrt(count),
            # mean root biomass (mg)
            mean_root_mass = mean(root_mass, na.rm = TRUE),
            sd_root_mass = sd(root_mass, na.rm = TRUE),
            SE_root_mass = sd_root_mass/sqrt(count),
            # ratio
            mean_ratio = mean(ratio, na.rm = TRUE),
            sd_ratio = sd(ratio, na.rm = TRUE),
            SE_ratio = sd_ratio/sqrt(count))
            # when adding more data, make sure to delete one of the ')' above in (count)) and add a comma

tp_all_long <- gather(tp_all, key = "trait", value = "measurement", height1:ratio)# use gather to stack the trait columns

tp_long_sum <- tp_all_long %>%
  group_by(type, trait) %>%
  summarize(count = n(),
            mean_trait = mean(measurement, na.rm = TRUE), sd_trait = sd(measurement, na.rm = TRUE),
            SE_trait = sd_trait/sqrt(count))
tp_long_sum$trait <- factor(tp_long_sum$trait, level = c("height1", "height2", "height3", "height4", "leaf1", "leaf2", "leaf3", "leaf4", "chloro1", "chloro2", "chloro3", "chloro4", "shoot_mass", "root_mass", "ratio", "nod_mass", "total_nod"))

# this includes controls
tp_long_sum_controlsplus <- tp_all_long %>%
  group_by(treatment, trait) %>%
  summarize(count = n(),
            mean_trait = mean(measurement, na.rm = TRUE), sd_trait = sd(measurement, na.rm = TRUE),
            SE_trait = sd_trait/sqrt(count))

tp_treated <- tp_all %>% # for ANOVA
  filter(type == "treated") %>%
  droplevels(.)

tp_treated_long <- gather(tp_treated, key = "trait", value = "measurement", height1:ratio)
tp_treated_long$trait <- factor(tp_treated_long$trait, level = c("height1", "height2", "height3", "height4", "leaf1", "leaf2", "leaf3", "leaf4", "chloro1", "chloro2", "chloro3", "chloro4", "shoot_mass", "root_mass", "ratio", "nod_mass", "total_nod"))

tp_treated_long_sum <- tp_treated_long %>%
  group_by(treatment, trait) %>%
  summarize(count = n(),
            mean_trait = mean(measurement, na.rm = TRUE), sd_trait = sd(measurement, na.rm = TRUE),
            SE_trait = sd_trait/sqrt(count))

#groups for chlorophyll through time
tp_treated_long_sum$chloro.time <- ifelse(tp_treated_long_sum$treatment == "141", "A", "B")
tp_treated_long_sum$timepoint <- ifelse(tp_treated_long_sum$trait == "height1", "1",
                    ifelse(tp_treated_long_sum$trait == "leaf1", "1",
                      ifelse(tp_treated_long_sum$trait == "chloro1", "1",
                        ifelse(tp_treated_long_sum$trait == "height2", "2",
                          ifelse(tp_treated_long_sum$trait == "leaf2", "2",
                            ifelse(tp_treated_long_sum$trait == "chloro2", "2",
                              ifelse(tp_treated_long_sum$trait == "height3", "3",
                                ifelse(tp_treated_long_sum$trait == "leaf3", "3",
                                  ifelse(tp_treated_long_sum$trait == "chloro3", "3", "4")))))))))

#groups for chlorophyll through time
tp_long_sum_controlsplus$chloro.time <- ifelse(tp_long_sum_controlsplus$treatment == "141", "A", "B")
tp_long_sum_controlsplus$timepoint <- ifelse(tp_long_sum_controlsplus$trait == "height1", "1",
                    ifelse(tp_long_sum_controlsplus$trait == "leaf1", "1",
                      ifelse(tp_long_sum_controlsplus$trait == "chloro1", "1",
                        ifelse(tp_long_sum_controlsplus$trait == "height2", "2",
                          ifelse(tp_long_sum_controlsplus$trait == "leaf2", "2",
                            ifelse(tp_long_sum_controlsplus$trait == "chloro2", "2",
                              ifelse(tp_long_sum_controlsplus$trait == "height3", "3",
                                ifelse(tp_long_sum_controlsplus$trait == "leaf3", "3",
                                  ifelse(tp_long_sum_controlsplus$trait == "chloro3", "3", "4")))))))))
```

# Linear mixed models with all data, pairwise contrasts for every treatment/control, fdr djustment, all traits
```{r}
lmm.all.shoot_mass <- lmer(shoot_mass ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.shoot_mass)
(anova_lmm.all.shoot_mass <- Anova(lmm.all.shoot_mass, type = 2))
lmm.all.shoot_mass.emms <- emmeans(lmm.all.shoot_mass, pairwise ~ treatment)
lmm.all.shoot_mass.emms.sum <- summary(lmm.all.shoot_mass.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.shoot_mass.emms.sum$contrasts, file= "./emmeans/emmeans_shoot_mass.csv")
plot(lmm.all.shoot_mass)

lmm.all.root_mass <- lmer(root_mass ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.root_mass)
(anova_lmm.all.root_mass <- Anova(lmm.all.root_mass, type = 2))
lmm.all.root_mass.emms <- emmeans(lmm.all.root_mass, pairwise ~ treatment)
lmm.all.root_mass.emms.sum <- summary(lmm.all.root_mass.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.root_mass.emms.sum$contrasts, file= "./emmeans/emmeans_root_mass.csv")
plot(lmm.all.root_mass)

lmm.all.ratio <- lmer(ratio ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.ratio)
(anova_lmm.all.ratio <- Anova(lmm.all.ratio, type = 2))
lmm.all.ratio.emms <- emmeans(lmm.all.ratio, pairwise ~ treatment)
lmm.all.ratio.emms.sum <- summary(lmm.all.ratio.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.ratio.emms.sum$contrasts, file= "./emmeans/emmeans_ratio.csv")
plot(lmm.all.ratio)

lmm.all.chloro4 <- lmer(chloro4 ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.chloro4)
(anova_lmm.all.chloro4 <- Anova(lmm.all.chloro4, type = 2))
lmm.all.chloro4.emms <- emmeans(lmm.all.chloro4, pairwise ~ treatment)
lmm.all.chloro4.emms.sum <- summary(lmm.all.chloro4.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.chloro4.emms.sum$contrasts, file= "./emmeans/emmeans_chloro4.csv")
plot(lmm.all.chloro4)

lmm.all.leaf4 <- lmer(leaf4 ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.leaf4)
(anova_lmm.all.leaf4 <- Anova(lmm.all.leaf4, type = 2))
lmm.all.leaf4.emms <- emmeans(lmm.all.leaf4, pairwise ~ treatment)
lmm.all.leaf4.emms.sum <- summary(lmm.all.leaf4.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.leaf4.emms.sum$contrasts, file= "./emmeans/emmeans_leaf4.csv")
plot(lmm.all.leaf4)

lmm.all.height4 <- lmer(height4 ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.height4)
(anova_lmm.all.height4 <- Anova(lmm.all.height4, type = 2))
lmm.all.height4.emms <- emmeans(lmm.all.height4, pairwise ~ treatment)
lmm.all.height4.emms.sum <- summary(lmm.all.height4.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.height4.emms.sum$contrasts, file= "./emmeans/emmeans_height4.csv")
plot(lmm.all.height4)

lmm.all.nod_mass <- lmer(nod_mass ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.nod_mass)
(anova_lmm.all.nod_mass <- Anova(lmm.all.nod_mass, type = 2))
lmm.all.nod_mass.emms <- emmeans(lmm.all.nod_mass, pairwise ~ treatment)
lmm.all.nod_mass.emms.sum <- summary(lmm.all.nod_mass.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.nod_mass.emms.sum$contrasts, file= "./emmeans/emmeans_nod_mass.csv")
plot(lmm.all.nod_mass)

lmm.all.total_nod <- lmer(total_nod ~ treatment + (1|rack), data = tp_all)
summary(lmm.all.total_nod)
(anova_lmm.all.total_nod <- Anova(lmm.all.total_nod, type = 2))
lmm.all.total_nod.emms <- emmeans(lmm.all.total_nod, pairwise ~ treatment)
lmm.all.total_nod.emms.sum <- summary(lmm.all.total_nod.emms, infer = c(TRUE,TRUE), adjust = "fdr")
write.csv(lmm.all.total_nod.emms.sum$contrasts, file= "./emmeans/emmeans_total_nod.csv")
plot(lmm.all.total_nod)

emmeans_all <- read.csv("./emmeans/emmeans_all.csv")
emmeans_all$significance <- ifelse(emmeans_all$p.value <= 0.05 & emmeans_all$p.value >= 0.01, "*",
                           ifelse(emmeans_all$p.value < 0.01 & emmeans_all$p.value >= 0.01, "**",
                                  ifelse(emmeans_all$p.value < 0.001 & emmeans_all$p.value >= 0.001, "**",
                                         ifelse(emmeans_all$p.value < 0.001 & emmeans_all$p.value >= 0.0001, "***",
                                                ifelse(emmeans_all$p.value < 0.0001, "****", "ns")))))
write.csv(emmeans_all, file="./emmeans/emmeans_all.csv")
```



# Stacked plot: shoot mass and total nod
```{r}
library(grid)
grid.newpage()
grid.draw(rbind(ggplotGrob(boxplot.shoot_mass.all), ggplotGrob(boxplot.total_nod.all), size = "last"))
```


# Plot: shoot mass
```{r}
# All treatments and controls
(boxplot.shoot_mass.all <- ggplot(tp_all %>%
  mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=shoot_mass)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Shoot mass (g)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.shoot_mass.all)
save_plot("./figures/boxplot_shoot_mass_all.png", boxplot.shoot_mass.all, base_asp = 3)

# 141 and co-inoculated only
(boxplot.shoot_mass <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=shoot_mass)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Shoot mass (g)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.shoot_mass)
save_plot("./figures/boxplot_shoot_mass.png", boxplot.shoot_mass, base_asp = 2)
```

# Plot: root mass
```{r}
# All treatments and controls
(boxplot.root_mass.all <- ggplot(tp_all %>% mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=root_mass)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Root mass (g)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.root_mass.all)
save_plot("./figures/boxplot_root_mass_all.png", boxplot.root_mass.all, base_asp = 3)

# 141 and co-inoculated only
(boxplot.root_mass <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "702A + 141", "717A + 141", "733B + 141")), aes(x=treatment, y=root_mass)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Root mass (g)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.root_mass)
save_plot("./figures/boxplot_root_mass.png", boxplot.root_mass, base_asp = 2)
```

# Plot: ratio
```{r}
# All treatments and controls
(boxplot.ratio.all <- ggplot(tp_all %>% mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=ratio)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Shoot:root mass ratio") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.ratio.all)
save_plot("./figures/boxplot_ratio_all.png", boxplot.ratio.all, base_asp = 3)

# 141 and co-inoculated only
(boxplot.ratio <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "702A + 141", "717A + 141", "733B + 141")), aes(x=treatment, y=ratio)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Shoot:root mass ratio") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.ratio)
save_plot("./figures/boxplot_ratio.png", boxplot.ratio, base_asp = 2)
```

# Plot: leaf number
```{r}
# All treatments and controls
(boxplot.leaf.all <- ggplot(tp_all %>% mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=leaf4)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Leaf count") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.leaf.all)
save_plot("./figures/boxplot_leaf_all.png", boxplot.leaf.all, base_asp = 3)

# 141 and co-inoculated only
(boxplot.leaf <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "702A + 141", "717A + 141", "733B + 141")), aes(x=treatment, y=leaf4)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Leaf count") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.leaf)
save_plot("./figures/boxplot_leaf.png", boxplot.leaf, base_asp = 2)
```


# Plot: height
```{r}
# All treatments and controls
(boxplot.height4.all <- ggplot(tp_all %>% mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=height4)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Shoot height (cm)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.height4.all)
save_plot("./figures/boxplot_height4_all.png", boxplot.height4.all, base_asp = 3)

# 141 and co-inoculated only
(boxplot.height4 <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "702A + 141", "717A + 141", "733B + 141")), aes(x=treatment, y=height4)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Shoot height (cm)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.height4)
save_plot("./figures/boxplot_height4.png", boxplot.height4, base_asp = 2)
```

# Plot: chloro
```{r}
# All treatments and controls
(boxplot.chloro4.all <- ggplot(tp_all %>% mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=chloro4)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Chlorophyll content (SPAD)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.chloro4.all)
save_plot("./figures/boxplot_chloro4_all.png", boxplot.chloro4.all, base_asp = 3)

# 141 and co-inoculated only
(boxplot.chloro4 <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "702A + 141", "717A + 141", "733B + 141")), aes(x=treatment, y=chloro4)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Chlorophyll content (SPAD)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.chloro4)
save_plot("./figures/boxplot_chloro4.png", boxplot.chloro4, base_asp = 2)
```

# Plot: nodule count
```{r}
# boxplot, all treatments and controls
(boxplot.total_nod.all <- ggplot(tp_all %>% mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=total_nod)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Nodule count") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.total_nod.all)
save_plot("./figures/boxplot_nodule_count_all.png", boxplot.total_nod.all, base_asp = 3)

# boxplot, 141 and co-inoculated treatments only
(boxplot.total_nod <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "702A + 141", "717A + 141", "733B + 141")), aes(x=treatment, y=total_nod)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Nodule count") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.total_nod.nErm)
save_plot("./figures/boxplot_nodule_count.png", boxplot.total_nod, base_asp = 2)
```

# Plot: nodule mass
```{r}
# boxplot, all treatments and controls
(boxplot.nod_mass.all <- ggplot(tp_all %>% mutate(treatment = fct_relevel(treatment, "InCtrl", "ExCtrl", "522", "717A", "702A", "733B", "141", "522 + 141", "717A + 141", "702A + 141", "733B + 141")), aes(x=treatment, y=(nod_mass)*1000)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Average nodule mass (mg)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.nod_mass.all)
save_plot("./figures/boxplot_nod_mass_all.png", boxplot.nod_mass.all, base_asp = 3)

# boxplot, 141 and co-inoculated treatments only
(boxplot.nod_mass <- ggplot(tp_all %>% filter(treatment == c("141", "522 + 141", "702A + 141", "717A + 141", "733B + 141")), aes(x=treatment, y=(nod_mass)*1000)) +
  geom_boxplot() +
  xlab("Treatment") +
  ylab("Average nodule mass (mg)") +
  #ggtitle("Average nodule count per plant at week 4") +
  theme_minimal_hgrid() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  )
plot(boxplot.nod_mass)
save_plot("./figures/boxplot_nod_mass.png", boxplot.nod_mass, base_asp = 2)
```

